# Generated by Django 4.1.5 on 2023-02-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+998(90) 123-45-67', max_length=20, verbose_name='Telefon nomeri')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('image', models.ImageField(upload_to='image/contact/', verbose_name='Súwret')),
                ('x_location', models.FloatField(verbose_name='Jaylasıw - X')),
                ('y_location', models.FloatField(verbose_name='Jaylasıw - Y')),
            ],
            options={
                'verbose_name': 'Baylanıs',
                'verbose_name_plural': 'Baylanıslar',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sipatlama')),
                ('image', models.ImageField(upload_to='', verbose_name='Súwret')),
            ],
            options={
                'verbose_name': 'Súwret',
                'verbose_name_plural': 'Súwretler',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Liga atı')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligalar',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=150, verbose_name='Liga atı')),
                ('kamanda1', models.CharField(max_length=50, verbose_name='1-kamanda')),
                ('sk1', models.IntegerField(verbose_name='Kamanda 1 gollar')),
                ('kamanda2', models.CharField(max_length=50, verbose_name='2-kamanda')),
                ('sk2', models.IntegerField(verbose_name='Kamanda 2 gollar')),
                ('date', models.DateField(verbose_name='Oqın waqtı (sáne)')),
                ('time', models.CharField(default='15:00 GMT+5', max_length=20, verbose_name='Oqın waqtı (saat)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Oyın',
                'verbose_name_plural': 'Oyınlar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Qısqa atama')),
                ('body', models.TextField(verbose_name='Tolıq jańalıq')),
                ('image', models.ImageField(upload_to='image/news/', verbose_name='Súwret')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sáne')),
            ],
            options={
                'verbose_name': 'Jańalıq',
                'verbose_name_plural': 'Jańalıqlar',
            },
        ),
        migrations.CreateModel(
            name='NextMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=150, verbose_name='Liga atı')),
                ('kamanda1', models.CharField(max_length=50, verbose_name='1-kamanda')),
                ('kamanda1_image', models.ImageField(upload_to='images/')),
                ('kamanda2', models.CharField(max_length=50, verbose_name='2-kamanda')),
                ('kamanda2_image', models.ImageField(upload_to='images/')),
                ('date', models.DateField(verbose_name='Oqın waqtı (sáne)')),
                ('time', models.CharField(default='15:00 GMT+5', max_length=25, verbose_name='Oqın waqtı (saat)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Keyingi oyın',
                'verbose_name_plural': 'Keyingi oyınlar',
            },
        ),
        migrations.CreateModel(
            name='OldMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=150, verbose_name='Liga atı')),
                ('kamanda1', models.CharField(max_length=50, verbose_name='1-kamanda')),
                ('kamanda1_image', models.ImageField(upload_to='images/')),
                ('sk1', models.IntegerField(verbose_name='1-kamanda gollar')),
                ('kamanda2', models.CharField(max_length=50, verbose_name='2-kamanda')),
                ('kamanda2_image', models.ImageField(upload_to='images/')),
                ('sk2', models.IntegerField(verbose_name='2-kamanda gollar')),
                ('date', models.DateField(verbose_name='Oqın waqtı (sáne)')),
                ('time', models.CharField(default='15:00 GMT+5', max_length=25, verbose_name='Oqın waqtı (saat)')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Aldınǵı oyın',
                'verbose_name_plural': 'Aldınǵı oyınlar',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/player/')),
                ('desk', models.TextField(null=True, verbose_name='Maǵlıwmat')),
                ('number_player', models.IntegerField(verbose_name='Oyınshı nomeri')),
                ('height', models.IntegerField(verbose_name='Oyınshı boyı')),
                ('weight', models.IntegerField(verbose_name='Oyınshı awırlıǵı')),
            ],
            options={
                'verbose_name': 'Oyınshı',
                'verbose_name_plural': 'Oyınshılar',
            },
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/player/')),
                ('desk', models.TextField(null=True, verbose_name='Maǵlıwmat')),
            ],
            options={
                'verbose_name': 'Trener',
                'verbose_name_plural': 'Trenerler',
            },
        ),
        migrations.CreateModel(
            name='LigaStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kamanda', models.CharField(max_length=100, verbose_name='Kamanda')),
                ('match', models.IntegerField(verbose_name='oyın')),
                ('score', models.IntegerField(verbose_name='ochko')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligateam', to='home.liga')),
            ],
            options={
                'verbose_name': 'Liga kamanda',
                'verbose_name_plural': 'Liga kamandaları',
            },
        ),
    ]
