# Generated by Django 4.1.5 on 2023-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='x_location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='y_location',
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.TextField(default='openstreetmap.org', verbose_name='Laylasıw ornı'),
        ),
    ]
