# Generated by Django 4.1.5 on 2023-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_contact_x_location_remove_contact_y_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_day',
            field=models.DateField(default='2023-02-25', verbose_name='Tuwılǵan sáne'),
        ),
        migrations.AlterField(
            model_name='player',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Tolıq atı'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(verbose_name='Oyınshı boyı'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Poziciya'),
        ),
    ]
