# Generated by Django 4.1.5 on 2023-02-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_instagram_contact_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image2',
            field=models.ImageField(null=True, upload_to='image/contact/', verbose_name='Súwret'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(upload_to='image/contact/', verbose_name='Súwret Fon'),
        ),
    ]
