# Generated by Django 4.1.5 on 2023-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contact_image2_alter_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image2',
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.ImageField(null=True, upload_to='image/news/', verbose_name='Súwret'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='image/news/', verbose_name='Súwret Fon'),
        ),
    ]
