# Generated by Django 4.1.5 on 2023-02-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(max_length=100, null=True, verbose_name='Qısqa maqala'),
        ),
    ]
