# Generated by Django 4.1.5 on 2023-02-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya ',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='caregory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='home.category'),
        ),
    ]
