# Generated by Django 4.1.5 on 2023-03-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rahbariyat_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook kanal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter kanal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube kanal'),
        ),
    ]
