# Generated by Django 4.1.5 on 2023-03-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contact_facebook_contact_twitter_contact_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligastat',
            name='match',
        ),
        migrations.RemoveField(
            model_name='ligastat',
            name='score',
        ),
        migrations.AddField(
            model_name='ligastat',
            name='drawn',
            field=models.IntegerField(default=0, verbose_name='Drawn'),
        ),
        migrations.AddField(
            model_name='ligastat',
            name='lost',
            field=models.IntegerField(default=0, verbose_name='Lost'),
        ),
        migrations.AddField(
            model_name='ligastat',
            name='played',
            field=models.IntegerField(default=0, verbose_name='Played'),
        ),
        migrations.AddField(
            model_name='ligastat',
            name='points',
            field=models.FloatField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='ligastat',
            name='won',
            field=models.IntegerField(default=0, verbose_name='Won'),
        ),
    ]
