# Generated by Django 4.1.5 on 2023-03-04 16:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_ligastat_match_remove_ligastat_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trener',
            options={'verbose_name': 'Trener ', 'verbose_name_plural': 'Trenerler'},
        ),
        migrations.RemoveField(
            model_name='trener',
            name='desk',
        ),
        migrations.AddField(
            model_name='trener',
            name='full_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' '),
        ),
        migrations.AddField(
            model_name='trener',
            name='role',
            field=models.CharField(default=' ', max_length=100, verbose_name='Lavozm'),
        ),
        migrations.AlterField(
            model_name='rahbariyat',
            name='full_information',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' '),
        ),
        migrations.AlterField(
            model_name='trener',
            name='image',
            field=models.ImageField(upload_to='image/trener/'),
        ),
    ]
