# Generated by Django 4.1.5 on 2023-03-04 17:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_trener_options_remove_trener_desk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PFC ARAL', max_length=150, verbose_name='Atama')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='Text')),
            ],
            options={
                'verbose_name': 'Klub tariyxı',
                'verbose_name_plural': 'Klub tariyxı',
            },
        ),
        migrations.CreateModel(
            name='U19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Atama')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='Text')),
            ],
            options={
                'verbose_name': 'U19',
                'verbose_name_plural': 'U19',
            },
        ),
    ]
