# Generated by Django 4.1.5 on 2023-03-04 17:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_clubhistory_u19'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PFC ARAL', max_length=150, verbose_name='Atama')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(default='Text')),
            ],
            options={
                'verbose_name': 'Stadion',
                'verbose_name_plural': 'Stadionlar',
            },
        ),
    ]
