# Generated by Django 4.1.5 on 2023-03-05 16:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_stadion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='oldmatch',
            name='full_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Oyın tolıq maǵlıwmat'),
        ),
    ]
